### ISSUE TITLE
NULL - Dual Box in restar server

### ISSUE THREAD

**Issue by u3games** [AthenaEventEngine/AthenaCore#156]
`java.lang.NullPointerException
    at com.github.u3games.eventengine.security.DualBoxProtection.removeConnection(DualBoxProtection.java:69)
    at com.github.u3games.eventengine.EventEngineManager.listenerOnLogout(EventEngineManager.java:281)
    at com.github.u3games.eventengine.adapter.EventEngineAdapter.onPlayerLogout(EventEngineAdapter.java:70)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.l2jserver.gameserver.model.events.listeners.AnnotationEventListener.executeEvent(AnnotationEventListener.java:51)
    at com.l2jserver.gameserver.model.events.EventDispatcher.notifyToListeners(EventDispatcher.java:242)
    at com.l2jserver.gameserver.model.events.EventDispatcher.notifyEventToMultipleContainers(EventDispatcher.java:178)
    at com.l2jserver.gameserver.model.events.EventDispatcher.lambda$notifyEventAsync$0(EventDispatcher.java:121)
    at com.l2jserver.gameserver.ThreadPoolManager$RunnableWrapper.run(ThreadPoolManager.java:89)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)`

**Comment by ghost** [comment]
On class EventEngineManager, over listenerOnLogout method, insert a if for check `if (player.getClient == null){ Do Something here }`

**Comment by Lucheti29** [comment]
@Sacrifice78 Could you make a fix?

**Comment by Sacrifice78** [comment]
posible fix #158

**Comment by ghost** [comment]
#158

**Comment by ghost** [comment]
Fixed in https://github.com/u3games/L2J_EventEngine/pull/158/commits/a9a1a3688421cbae3a0bf9eb43b0ab7be23d6897
