### ISSUE TITLE
DualBoxProtection - NullPointerException

### ISSUE THREAD

**Issue by u3games** [AthenaEventEngine/AthenaCore#162]
java.lang.NullPointerException
	at com.github.u3games.eventengine.security.DualBoxProtection.removeConnection(DualBoxProtection.java:69)
	at com.github.u3games.eventengine.EventEngineManager.listenerOnLogout(EventEngineManager.java:281)
	at com.github.u3games.eventengine.adapter.EventEngineAdapter.onPlayerLogout(EventEngineAdapter.java:70)
	at sun.reflect.GeneratedMethodAccessor27.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.l2jserver.gameserver.model.events.listeners.AnnotationEventListener.executeEvent(AnnotationEventListener.java:51)
	at com.l2jserver.gameserver.model.events.EventDispatcher.notifyToListeners(EventDispatcher.java:242)
	at com.l2jserver.gameserver.model.events.EventDispatcher.notifyEventToMultipleContainers(EventDispatcher.java:178)
	at com.l2jserver.gameserver.model.events.EventDispatcher.lambda$notifyEventAsync$0(EventDispatcher.java:121)
	at com.l2jserver.gameserver.ThreadPoolManager$RunnableWrapper.run(ThreadPoolManager.java:89)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

**Comment by Lucheti29** [comment]
This occurs because the client is detached before the onPlayerLogout event is called. I know how to fix it anyway.

**Comment by u3games** [comment]
Fix NPE:

![photo_2017-01-20_19-58-43](https://cloud.githubusercontent.com/assets/5102409/22161489/d34c0ece-df4a-11e6-847c-db511f72d2b3.jpg)

--> https://github.com/AthenaEventEngine/AthenaCore/pull/163
